# Generated by Django 5.0.7 on 2024-08-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outcomes',
            new_name='Outcome',
        ),
    ]
