# Generated by Django 5.0.7 on 2024-07-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_twitch_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twitch_channel',
        ),
    ]
