# Generated by Django 5.0.7 on 2024-08-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_streamer_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
